# 多前缀匹配，多上游轮询
[[routes]]
prefix = ["/user", "/users"]
upstream = ["http://localhost:30000", "http://localhost:30001", "http://localhost:30002"]

# 单前缀匹配，多上游轮询
[[routes]]
prefix = "/api/user/{id}"
upstream = ["http://localhost:30000", "http://localhost:30001", "http://localhost:30002"]
strategy = "iphash"

# 多前缀匹配，多上游轮询
#[[routes]]
#prefix = ["/api/user/{id:[0-9]+}", "/api/users/{id:[0-9]+}"]
#upstream = ["http://localhost:30000", "http://localhost:30001", "http://localhost:30002"]
#strategy = "random"

# 多段通配符匹配，多上游轮询
[[routes]]
prefix = "/static/**"
upstream = ["http://localhost:30000", "http://localhost:30001", "http://localhost:30002"]

# 单字符通配符匹配，多上游轮询
[[routes]]
prefix = "/files/?.txt"
upstream = ["http://localhost:30000", "http://localhost:30001", "http://localhost:30002"]

# 复杂模式匹配，多上游轮询
[[routes]]
prefix = "/api/v{version}/user/{id:[0-9]+}/posts/**"
upstream = ["http://localhost:30000", "http://localhost:30001", "http://localhost:30002"]

# 认证相关路径，多上游轮询
[[routes]]
prefix = ["/auth", "/login"]
upstream = ["http://localhost:30000", "http://localhost:30001", "http://localhost:30002"]

# 根路径，多上游轮询
[[routes]]
prefix = "/"
upstream = ["http://localhost:30000", "http://localhost:30001", "http://localhost:30002"]
